services:
  pytest_runner:
    build: .
    image: playwright
    command: pytest tests/test_pdp.py -k test_select_size
    volumes:
      - .:/test_project

  report:
    image: playwright
    volumes:
      - .:/test_project
    command: /bin/sh -c "allure generate allure_results --clean -o allure_report"