name: UI tests

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps firefox
          
      - name: Run UI-tests with pytest and generate Allure results
        run: |
          pytest tests/test_pdp.py -k test_select_size --reruns 2 --alluredir=allure_results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure_results
          path: allure_results


  publish-report:
    if: always()
    needs: [ ui-tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure_results
          path: allure_results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          allure_results: allure_results
          allure_history: allure_history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure_history